# Generated by Django 4.2.3 on 2023-07-14 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_mang', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceDetails',
            new_name='InvoiceDetail',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice',
            new_name='invoice_number',
        ),
    ]
